# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Config.create([
                  {
                      foodcost: 50,
                      allocationcost: 100,
                      fooddeadline: DateTime.parse('2015-11-02 00:00:00 CDT'),
                      allocationdeadline: DateTime.parse('2015-11-02 00:00:00 CDT'),
                      max_food: 500,
                      max_allocation: 224
                  }
              ])

Hotel.create!([
                {name: "Hotel Portonovo Plaza", address: "Lopez Mateos Sur 2400", phone: "3339159600", email: "", cost: "habitación para 1 o 2 personas $600°° por persona extra $100", url: "http://www.hotelportonovoplaza.com/expo/index.html", gmaps: "Hotel%20Portonovo%20Plaza%20Expo%2C%20Avenida%20Lopez%20Mateos%20Sur%2C%20Guadalajara%2C%20Mexico", comments: "No incluye alimentos ni transporte.", has_discount: true},
                {name: "Paradise Real Guadalajara", address: "Periférico Sur 7200, Fracc. Industrial Camino Tlaquepaque, Jalisco", phone: "3331330138", email: "hotelparadisegdlventas@hotmail.com", cost: "$550 habitación doble 2 personas y 2 menores de 12 años, persona adicional $150", url: "http://www.hotelesparadise.com/contactoguadalajara.html", gmaps: "Paradise%20Real%20De%20Guadalajara%2C%20S.A.%20De%20C.V.%2C%20Anillo%20Perif%C3%A9rico%20Sur%20Manuel%20G%C3%B3mez%20Morin%2C%20Santa%20Mar%C3%ADa%20Tequepexpan%2C%20Tlaquepaque%2C%20Mexico", comments: "No incluye alimentos ni transporte.", has_discount: true},
                {name: "Aurea Hotel & Suites", address: "Av. Lopez Mateos Sur #3848, col. La Calma", phone: "3336313628", email: "", cost: "Suite sencilla $ 810, Suite doble $ 810, Jr. Suite $ 960, Persona extra $ 130", url: "http://www.suitesaurea.com/", gmaps: "%C3%81urea%20Hotel%20%26%20Suites%2C%20La%20Calma%2C%20Zapopan%2C%20Mexico", comments: "No incluye alimentos ni transporte.", has_discount: true},
                {name: "Hotel Suites Chapalita", address: "Av. Lopez Mateos Sur #1617", phone: "3331227710", email: "", cost: "Habitación 2 personas: $510°° Habitación 3 personas: $560°° Habitación 4 personas $610°° (pagando en efectivo obtendrán un 10% de descuento)", url: "http://www.hotelsuiteschapalita.com/", gmaps: "Hotel%20Suites%20Chapalita", comments: "No incluye alimentos ni transporte.", has_discount: true},
                {name: "Holliday Inn Express Iteso", address: "Av Camino Al Iteso 8650, Casi Periférico Sur", phone: "3338841234", email: "", cost: "Habitación doble $1000 + Imp \r\nA partir de 10 habitaciones $890 + imp", url: "http://www.ihg.com/holidayinnexpress/hotels/us/es/guadalajara/gdlit/hoteldetail", gmaps: "Holiday%20Inn%20Express%20Guadalajara%20Iteso%2C%20Avenida%20Camino%20Al%20Iteso%2C%20Santa%20Mar%C3%ADa%20Tequepexpan%2C%20Tlaquepaque%2C%20Mexico", comments: "Cortesía (desayuno Express, internet, estacionamiento, Transportacion previa reservación)", has_discount: true},
                {name: "Hotel IBIS", address: "Av Mariano Otero no 1400 Col Jardines Del Bosque", phone: "3338809600", email: "", cost: "Habitación (1 cama matrimonial 1 o 2 personas) $599 \r\nHabitación (2 camas individuales 1 o 2 personas) $699 Persona extra $119°°", url: "http://www.ibis.com/es/hotel-3355-ibis-guadalajara-expo/index.shtml", gmaps: "Hotel%20ibis%20Guadalajara%20Expo%2C%20Guadalajara%2C%20Mexico", comments: "No incluye alimentos ni transporte.", has_discount: false},
                {name: "CITY Junior Periférico Sur", address: "Periférico Sur, entre Av. Adolf Horn y Casi carretera Chapala", phone: "3336685630", email: "", cost: "Habitación sencilla $ 654 (1 cama queen 1 o 2 personas) \r\nHabitación doble $737.30 (2 camas individuales 1 o 2 personas)", url: "http://cityjunior.hotelescity.com/es/hoteles/city-junior-guadalajara-periferico-sur/informacion-general.aspx?hoteldatos=0CJCJGPS", gmaps: "Hotel%20City%20Express%20Junior%20Guadalajara%20Periferico%20Sur%2C%20Tlaquepaque%2C%20Mexico", comments: "Incluye desayuno/ internet/ estacionamiento / Transporte 10 km a la redonda previa reservación", has_discount: true}
              ])

State.create([
                { key: '01', name: 'Aguascalientes', short: 'Ags.'},
                { key: '02', name: 'Baja California', short: 'BC'},
                { key: '03', name: 'Baja California Sur', short: 'BCS'},
                { key: '04', name: 'Campeche', short: 'Camp.'},
                { key: '05', name: 'Coahuila de Zaragoza', short: 'Coah.'},
                { key: '06', name: 'Colima', short: 'Col.'},
                { key: '07', name: 'Chiapas', short: 'Chis.'},
                { key: '08', name: 'Chihuahua', short: 'Chih.'},
                { key: '09', name: 'Distrito Federal', short: 'DF'},
                { key: '10', name: 'Durango', short: 'Dgo.'},
                { key: '11', name: 'Guanajuato', short: 'Gto.'},
                { key: '12', name: 'Guerrero', short: 'Gro.'},
                { key: '13', name: 'Hidalgo', short: 'Hgo.'},
                { key: '14', name: 'Jalisco', short: 'Jal.'},
                { key: '15', name: 'México', short: 'Mex.'},
                { key: '16', name: 'Michoacán', short: 'Mich.'},
                { key: '17', name: 'Morelos', short: 'Mor.'},
                { key: '18', name: 'Nayarit', short: 'Nay.'},
                { key: '19', name: 'Nuevo León', short: 'NL'},
                { key: '20', name: 'Oaxaca', short: 'Oax.'},
                { key: '21', name: 'Puebla', short: 'Pue.'},
                { key: '22', name: 'Querétaro', short: 'Qro.'},
                { key: '23', name: 'Quintana Roo', short: 'Q. Roo'},
                { key: '24', name: 'San Luis Potosí', short: 'SLP'},
                { key: '25', name: 'Sinaloa', short: 'Sin.'},
                { key: '26', name: 'Sonora', short: 'Son.'},
                { key: '27', name: 'Tabasco', short: 'Tab.'},
                { key: '28', name: 'Tamaulipas', short: 'Tamps.'},
                { key: '29', name: 'Tlaxcala', short: 'Tlax.'},
                { key: '30', name: 'Veracruz', short: 'Ver.'},
                { key: '31', name: 'Yucatán', short: 'Yuc.'},
                { key: '32', name: 'Zacatecas', short: 'Zac.'},
             ])

Country.create([
                   { iso: 'AF', name: 'Afganistán' },
                   { iso: 'AX', name: 'Islas Gland' },
                   { iso: 'AL', name: 'Albania' },
                   { iso: 'DE', name: 'Alemania' },
                   { iso: 'AD', name: 'Andorra' },
                   { iso: 'AO', name: 'Angola' },
                   { iso: 'AI', name: 'Anguilla' },
                   { iso: 'AQ', name: 'Antártida' },
                   { iso: 'AG', name: 'Antigua y Barbuda' },
                   { iso: 'AN', name: 'Antillas Holandesas' },
                   { iso: 'SA', name: 'Arabia Saudí' },
                   { iso: 'DZ', name: 'Argelia' },
                   { iso: 'AR', name: 'Argentina' },
                   { iso: 'AM', name: 'Armenia' },
                   { iso: 'AW', name: 'Aruba' },
                   { iso: 'AU', name: 'Australia' },
                   { iso: 'AT', name: 'Austria' },
                   { iso: 'AZ', name: 'Azerbaiyán' },
                   { iso: 'BS', name: 'Bahamas' },
                   { iso: 'BH', name: 'Bahréin' },
                   { iso: 'BD', name: 'Bangladesh' },
                   { iso: 'BB', name: 'Barbados' },
                   { iso: 'BY', name: 'Bielorrusia' },
                   { iso: 'BE', name: 'Bélgica' },
                   { iso: 'BZ', name: 'Belice' },
                   { iso: 'BJ', name: 'Benin' },
                   { iso: 'BM', name: 'Bermudas' },
                   { iso: 'BT', name: 'Bhután' },
                   { iso: 'BO', name: 'Bolivia' },
                   { iso: 'BA', name: 'Bosnia y Herzegovina' },
                   { iso: 'BW', name: 'Botsuana' },
                   { iso: 'BV', name: 'Isla Bouvet' },
                   { iso: 'BR', name: 'Brasil' },
                   { iso: 'BN', name: 'Brunéi' },
                   { iso: 'BG', name: 'Bulgaria' },
                   { iso: 'BF', name: 'Burkina Faso' },
                   { iso: 'BI', name: 'Burundi' },
                   { iso: 'CV', name: 'Cabo Verde' },
                   { iso: 'KY', name: 'Islas Caimán' },
                   { iso: 'KH', name: 'Camboya' },
                   { iso: 'CM', name: 'Camerún' },
                   { iso: 'CA', name: 'Canadá' },
                   { iso: 'CF', name: 'República Centroafricana' },
                   { iso: 'TD', name: 'Chad' },
                   { iso: 'CZ', name: 'República Checa' },
                   { iso: 'CL', name: 'Chile' },
                   { iso: 'CN', name: 'China' },
                   { iso: 'CY', name: 'Chipre' },
                   { iso: 'CX', name: 'Isla de Navidad' },
                   { iso: 'VA', name: 'Ciudad del Vaticano' },
                   { iso: 'CC', name: 'Islas Cocos' },
                   { iso: 'CO', name: 'Colombia' },
                   { iso: 'KM', name: 'Comoras' },
                   { iso: 'CD', name: 'República Democrática del Congo' },
                   { iso: 'CG', name: 'Congo' },
                   { iso: 'CK', name: 'Islas Cook' },
                   { iso: 'KP', name: 'Corea del Norte' },
                   { iso: 'KR', name: 'Corea del Sur' },
                   { iso: 'CI', name: 'Costa de Marfil' },
                   { iso: 'CR', name: 'Costa Rica' },
                   { iso: 'HR', name: 'Croacia' },
                   { iso: 'CU', name: 'Cuba' },
                   { iso: 'DK', name: 'Dinamarca' },
                   { iso: 'DM', name: 'Dominica' },
                   { iso: 'DO', name: 'República Dominicana' },
                   { iso: 'EC', name: 'Ecuador' },
                   { iso: 'EG', name: 'Egipto' },
                   { iso: 'SV', name: 'El Salvador' },
                   { iso: 'AE', name: 'Emiratos Árabes Unidos' },
                   { iso: 'ER', name: 'Eritrea' },
                   { iso: 'SK', name: 'Eslovaquia' },
                   { iso: 'SI', name: 'Eslovenia' },
                   { iso: 'ES', name: 'España' },
                   { iso: 'UM', name: 'Islas ultramarinas de Estados Unidos' },
                   { iso: 'US', name: 'Estados Unidos' },
                   { iso: 'EE', name: 'Estonia' },
                   { iso: 'ET', name: 'Etiopía' },
                   { iso: 'FO', name: 'Islas Feroe' },
                   { iso: 'PH', name: 'Filipinas' },
                   { iso: 'FI', name: 'Finlandia' },
                   { iso: 'FJ', name: 'Fiyi' },
                   { iso: 'FR', name: 'Francia' },
                   { iso: 'GA', name: 'Gabón' },
                   { iso: 'GM', name: 'Gambia' },
                   { iso: 'GE', name: 'Georgia' },
                   { iso: 'GS', name: 'Islas Georgias del Sur y Sandwich del Sur' },
                   { iso: 'GH', name: 'Ghana' },
                   { iso: 'GI', name: 'Gibraltar' },
                   { iso: 'GD', name: 'Granada' },
                   { iso: 'GR', name: 'Grecia' },
                   { iso: 'GL', name: 'Groenlandia' },
                   { iso: 'GP', name: 'Guadalupe' },
                   { iso: 'GU', name: 'Guam' },
                   { iso: 'GT', name: 'Guatemala' },
                   { iso: 'GF', name: 'Guayana Francesa' },
                   { iso: 'GN', name: 'Guinea' },
                   { iso: 'GQ', name: 'Guinea Ecuatorial' },
                   { iso: 'GW', name: 'Guinea-Bissau' },
                   { iso: 'GY', name: 'Guyana' },
                   { iso: 'HT', name: 'Haití' },
                   { iso: 'HM', name: 'Islas Heard y McDonald' },
                   { iso: 'HN', name: 'Honduras' },
                   { iso: 'HK', name: 'Hong Kong' },
                   { iso: 'HU', name: 'Hungría' },
                   { iso: 'IN', name: 'India' },
                   { iso: 'ID', name: 'Indonesia' },
                   { iso: 'IR', name: 'Irán' },
                   { iso: 'IQ', name: 'Iraq' },
                   { iso: 'IE', name: 'Irlanda' },
                   { iso: 'IS', name: 'Islandia' },
                   { iso: 'IL', name: 'Israel' },
                   { iso: 'IT', name: 'Italia' },
                   { iso: 'JM', name: 'Jamaica' },
                   { iso: 'JP', name: 'Japón' },
                   { iso: 'JO', name: 'Jordania' },
                   { iso: 'KZ', name: 'Kazajstán' },
                   { iso: 'KE', name: 'Kenia' },
                   { iso: 'KG', name: 'Kirguistán' },
                   { iso: 'KI', name: 'Kiribati' },
                   { iso: 'KW', name: 'Kuwait' },
                   { iso: 'LA', name: 'Laos' },
                   { iso: 'LS', name: 'Lesotho' },
                   { iso: 'LV', name: 'Letonia' },
                   { iso: 'LB', name: 'Líbano' },
                   { iso: 'LR', name: 'Liberia' },
                   { iso: 'LY', name: 'Libia' },
                   { iso: 'LI', name: 'Liechtenstein' },
                   { iso: 'LT', name: 'Lituania' },
                   { iso: 'LU', name: 'Luxemburgo' },
                   { iso: 'MO', name: 'Macao' },
                   { iso: 'MK', name: 'ARY Macedonia' },
                   { iso: 'MG', name: 'Madagascar' },
                   { iso: 'MY', name: 'Malasia' },
                   { iso: 'MW', name: 'Malawi' },
                   { iso: 'MV', name: 'Maldivas' },
                   { iso: 'ML', name: 'Malí' },
                   { iso: 'MT', name: 'Malta' },
                   { iso: 'FK', name: 'Islas Malvinas' },
                   { iso: 'MP', name: 'Islas Marianas del Norte' },
                   { iso: 'MA', name: 'Marruecos' },
                   { iso: 'MH', name: 'Islas Marshall' },
                   { iso: 'MQ', name: 'Martinica' },
                   { iso: 'MU', name: 'Mauricio' },
                   { iso: 'MR', name: 'Mauritania' },
                   { iso: 'YT', name: 'Mayotte' },
                   { iso: 'MX', name: 'México' },
                   { iso: 'FM', name: 'Micronesia' },
                   { iso: 'MD', name: 'Moldavia' },
                   { iso: 'MC', name: 'Mónaco' },
                   { iso: 'MN', name: 'Mongolia' },
                   { iso: 'MS', name: 'Montserrat' },
                   { iso: 'MZ', name: 'Mozambique' },
                   { iso: 'MM', name: 'Myanmar' },
                   { iso: 'NA', name: 'Namibia' },
                   { iso: 'NR', name: 'Nauru' },
                   { iso: 'NP', name: 'Nepal' },
                   { iso: 'NI', name: 'Nicaragua' },
                   { iso: 'NE', name: 'Níger' },
                   { iso: 'NG', name: 'Nigeria' },
                   { iso: 'NU', name: 'Niue' },
                   { iso: 'NF', name: 'Isla Norfolk' },
                   { iso: 'NO', name: 'Noruega' },
                   { iso: 'NC', name: 'Nueva Caledonia' },
                   { iso: 'NZ', name: 'Nueva Zelanda' },
                   { iso: 'OM', name: 'Omán' },
                   { iso: 'NL', name: 'Países Bajos' },
                   { iso: 'PK', name: 'Pakistán' },
                   { iso: 'PW', name: 'Palau' },
                   { iso: 'PS', name: 'Palestina' },
                   { iso: 'PA', name: 'Panamá' },
                   { iso: 'PG', name: 'Papúa Nueva Guinea' },
                   { iso: 'PY', name: 'Paraguay' },
                   { iso: 'PE', name: 'Perú' },
                   { iso: 'PN', name: 'Islas Pitcairn' },
                   { iso: 'PF', name: 'Polinesia Francesa' },
                   { iso: 'PL', name: 'Polonia' },
                   { iso: 'PT', name: 'Portugal' },
                   { iso: 'PR', name: 'Puerto Rico' },
                   { iso: 'QA', name: 'Qatar' },
                   { iso: 'GB', name: 'Reino Unido' },
                   { iso: 'RE', name: 'Reunión' },
                   { iso: 'RW', name: 'Ruanda' },
                   { iso: 'RO', name: 'Rumania' },
                   { iso: 'RU', name: 'Rusia' },
                   { iso: 'EH', name: 'Sahara Occidental' },
                   { iso: 'SB', name: 'Islas Salomón' },
                   { iso: 'WS', name: 'Samoa' },
                   { iso: 'AS', name: 'Samoa Americana' },
                   { iso: 'KN', name: 'San Cristóbal y Nevis' },
                   { iso: 'SM', name: 'San Marino' },
                   { iso: 'PM', name: 'San Pedro y Miquelón' },
                   { iso: 'VC', name: 'San Vicente y las Granadinas' },
                   { iso: 'SH', name: 'Santa Helena' },
                   { iso: 'LC', name: 'Santa Lucía' },
                   { iso: 'ST', name: 'Santo Tomé y Príncipe' },
                   { iso: 'SN', name: 'Senegal' },
                   { iso: 'CS', name: 'Serbia y Montenegro' },
                   { iso: 'SC', name: 'Seychelles' },
                   { iso: 'SL', name: 'Sierra Leona' },
                   { iso: 'SG', name: 'Singapur' },
                   { iso: 'SY', name: 'Siria' },
                   { iso: 'SO', name: 'Somalia' },
                   { iso: 'LK', name: 'Sri Lanka' },
                   { iso: 'SZ', name: 'Suazilandia' },
                   { iso: 'ZA', name: 'Sudáfrica' },
                   { iso: 'SD', name: 'Sudán' },
                   { iso: 'SE', name: 'Suecia' },
                   { iso: 'CH', name: 'Suiza' },
                   { iso: 'SR', name: 'Surinam' },
                   { iso: 'SJ', name: 'Svalbard y Jan Mayen' },
                   { iso: 'TH', name: 'Tailandia' },
                   { iso: 'TW', name: 'Taiwán' },
                   { iso: 'TZ', name: 'Tanzania' },
                   { iso: 'TJ', name: 'Tayikistán' },
                   { iso: 'IO', name: 'Territorio Británico del Océano Índico' },
                   { iso: 'TF', name: 'Territorios Australes Franceses' },
                   { iso: 'TL', name: 'Timor Oriental' },
                   { iso: 'TG', name: 'Togo' },
                   { iso: 'TK', name: 'Tokelau' },
                   { iso: 'TO', name: 'Tonga' },
                   { iso: 'TT', name: 'Trinidad y Tobago' },
                   { iso: 'TN', name: 'Túnez' },
                   { iso: 'TC', name: 'Islas Turcas y Caicos' },
                   { iso: 'TM', name: 'Turkmenistán' },
                   { iso: 'TR', name: 'Turquía' },
                   { iso: 'TV', name: 'Tuvalu' },
                   { iso: 'UA', name: 'Ucrania' },
                   { iso: 'UG', name: 'Uganda' },
                   { iso: 'UY', name: 'Uruguay' },
                   { iso: 'UZ', name: 'Uzbekistán' },
                   { iso: 'VU', name: 'Vanuatu' },
                   { iso: 'VE', name: 'Venezuela' },
                   { iso: 'VN', name: 'Vietnam' },
                   { iso: 'VG', name: 'Islas Vírgenes Británicas' },
                   { iso: 'VI', name: 'Islas Vírgenes de los Estados Unidos' },
                   { iso: 'WF', name: 'Wallis y Futuna' },
                   { iso: 'YE', name: 'Yemen' },
                   { iso: 'DJ', name: 'Yibuti' },
                   { iso: 'ZM', name: 'Zambia' },
                   { iso: 'ZW', name: 'Zimbabue' },
               ])